// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type SessionResp = {
    user: User;
    session: Token;
};

export type User = {
    id: string;
    userName: string;
    email: string;
    pfpUrl: string;
};

export type Token = {
    id: string;
    userId: string;
    type: 'WEB_SESSION' | 'API_KEY' | null;
    name: string | null;
    scopes: string | number | boolean | unknown | {
        [key: string]: unknown;
    } | Array<unknown>;
    createdAt: string | null;
    expiresAt: string | null;
};

export type AuthResponseSchema = {
    token: string;
    tokenHash: string;
};

export type Status = {
    message: string;
};

export type GetV1SessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/session';
};

export type GetV1SessionResponses = {
    /**
     * Details about the user and token used to acquire the user.
     */
    200: SessionResp;
};

export type GetV1SessionResponse = GetV1SessionResponses[keyof GetV1SessionResponses];

export type PostV1AuthGithubData = {
    body?: {
        code: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/github';
};

export type PostV1AuthGithubErrors = {
    /**
     * Bad Request
     */
    400: {
        code: 'BAD_TOKEN';
        message: string;
    };
    /**
     * Unauthorized
     */
    401: {
        code: 'EXPIRED_CREDENTIALS' | 'NO_VERIFIED_EMAIL';
        message: string;
    };
    /**
     * Internal Error
     */
    500: {
        code: 'INTERNAL_ERROR' | 'EXISTING_ACCOUNT';
        message: string;
    };
};

export type PostV1AuthGithubError = PostV1AuthGithubErrors[keyof PostV1AuthGithubErrors];

export type PostV1AuthGithubResponses = {
    /**
     * A private route to handle generation of tokens and auth. This route will not work if the code query param is not generated using the correct oAuth app.
     */
    200: AuthResponseSchema;
};

export type PostV1AuthGithubResponse = PostV1AuthGithubResponses[keyof PostV1AuthGithubResponses];

export type GetV1ResourcesByLocatorData = {
    body?: never;
    path: {
        locator: string;
    };
    query?: never;
    url: '/v1/resources/{locator}';
};

export type GetV1ResourcesByLocatorErrors = {
    /**
     * Resource not found
     */
    404: {
        code: 'NOT_FOUND';
        message: string;
    };
    /**
     * Internal Error
     */
    500: {
        code: 'INTERNAL_ERROR';
        message: string;
    };
};

export type GetV1ResourcesByLocatorError = GetV1ResourcesByLocatorErrors[keyof GetV1ResourcesByLocatorErrors];

export type GetV1ResourcesByLocatorResponses = {
    /**
     * A single resource
     */
    200: {
        resource: {
            id: string;
            ownerId: string;
            name: string;
            slug: string;
            description: string;
            category: 'Administration' | 'Tools' | 'Security' | 'Social' | 'Optimization' | 'Mechanics' | 'Libraries' | 'World Generation' | 'Economy' | 'Cosmetics' | 'Minigames';
            price: number;
            createdAt: string | null;
            updatedAt: string | null;
        };
    };
};

export type GetV1ResourcesByLocatorResponse = GetV1ResourcesByLocatorResponses[keyof GetV1ResourcesByLocatorResponses];

export type GetV1ResourcesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter resources by ownerId
         */
        ownerId?: string;
    };
    url: '/v1/resources';
};

export type GetV1ResourcesErrors = {
    /**
     * Internal Error
     */
    500: {
        code: 'INTERNAL_ERROR';
        message: string;
    };
};

export type GetV1ResourcesError = GetV1ResourcesErrors[keyof GetV1ResourcesErrors];

export type GetV1ResourcesResponses = {
    /**
     * A list of resources
     */
    200: {
        resources: Array<{
            id: string;
            ownerId: string;
            name: string;
            slug: string;
            description: string;
            category: 'Administration' | 'Tools' | 'Security' | 'Social' | 'Optimization' | 'Mechanics' | 'Libraries' | 'World Generation' | 'Economy' | 'Cosmetics' | 'Minigames';
            price: number;
            createdAt: string | null;
            updatedAt: string | null;
        }>;
    };
};

export type GetV1ResourcesResponse = GetV1ResourcesResponses[keyof GetV1ResourcesResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type GetStatusResponses = {
    /**
     * Looking Good!
     */
    200: Status;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];
