// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type SessionResp = {
    user: User;
    token: Token;
};

export type User = {
    id: string;
    userName: string;
    email: string;
    pfpUrl: string;
};

export type Token = {
    id: string;
    userId: string;
    type: 'WEB_SESSION' | 'API_KEY' | null;
    name: string | null;
    scopes: string | number | boolean | unknown | {
        [key: string]: unknown;
    } | Array<unknown>;
    createdAt: string | null;
    expiresAt: string | null;
};

export type Status = {
    message: string;
};

export type GetV1SessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/session';
};

export type GetV1SessionResponses = {
    /**
     * Details about the user and token used to acquire the user.
     */
    200: SessionResp;
};

export type GetV1SessionResponse = GetV1SessionResponses[keyof GetV1SessionResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type GetStatusResponses = {
    /**
     * Looking Good!
     */
    200: Status;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];
