// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8787' | (string & {});
};

export type Status = {
    message: string;
};

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type GetStatusResponses = {
    /**
     * Looking Good!
     */
    200: Status;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];
